# pyproject.toml
[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = [
  "catalog/migrations/",
  "**/migrations/",
  ".venv/",
  "__pycache__/",
  "*.pyc"
]
