# Generated by Django 5.2.3 on 2025-06-26 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="horizonresult",
            options={"ordering": ["event_date", "ticker", "horizon"]},
        ),
        migrations.AddField(
            model_name="eventdate",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="horizonresult",
            name="event_date",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="horizon_results",
                to="catalog.eventdate",
            ),
        ),
        migrations.AddField(
            model_name="horizonresult",
            name="ticker",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.CreateModel(
            name="SuggestedStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[("positive", "Up"), ("negative", "Down")], max_length=8
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_stocks",
                        to="catalog.analysispost",
                    ),
                ),
            ],
        ),
    ]
