# Generated by Django 5.2.3 on 2025-06-26 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_horizonresult_options_eventdate_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="horizonresult",
            name="event_date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="horizon_results",
                to="catalog.eventdate",
            ),
        ),
        migrations.AlterField(
            model_name="horizonresult",
            name="ticker",
            field=models.CharField(max_length=10),
        ),
    ]
