# Generated by Django 5.2.3 on 2025-06-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_horizonresult_event_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="horizonresult",
            options={},
        ),
        migrations.RemoveField(
            model_name="eventdate",
            name="description",
        ),
        migrations.RemoveField(
            model_name="eventdate",
            name="event_date",
        ),
        migrations.RemoveField(
            model_name="eventdate",
            name="post",
        ),
        migrations.RemoveField(
            model_name="horizonresult",
            name="event_date",
        ),
        migrations.RemoveField(
            model_name="horizonresult",
            name="horizon",
        ),
        migrations.RemoveField(
            model_name="horizonresult",
            name="post",
        ),
        migrations.RemoveField(
            model_name="horizonresult",
            name="return_value",
        ),
        migrations.RemoveField(
            model_name="horizonresult",
            name="ticker",
        ),
        migrations.RemoveField(
            model_name="suggestedstock",
            name="description",
        ),
        migrations.RemoveField(
            model_name="suggestedstock",
            name="name",
        ),
        migrations.RemoveField(
            model_name="suggestedstock",
            name="post",
        ),
        migrations.RemoveField(
            model_name="suggestedstock",
            name="sentiment",
        ),
        migrations.RemoveField(
            model_name="suggestedstock",
            name="ticker",
        ),
        migrations.AddField(
            model_name="analysispost",
            name="events_data",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="analysispost",
            name="results_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="analysispost",
            name="stocks_data",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
